### ISSUE TITLE
Tricky way of printing buffer

### ISSUE THREAD

**Issue by spolischook** [kpango/glg#110]
I found that code into the `Glg.out` method:

```go
_, err = fmt.Fprintf(log.writer, *(*string)(unsafe.Pointer(&buf)), val...)
```
I guess you have a serious reason to get data from `buf` in such a tricky way.
I'm curious why you do so?

@kpango

**Comment by kpango** [comment]
@spolischook Hi.

This is the usual way to convert a byte slice to a string type in zero copy.
It is also used in the official package `strings.Builder.String()`.
The reason why I didn't use `strings.Builder` in this project is due to the structure of the Buffer Pool in glg, which reduces the memory allocation between each output and reuses `bytes.Buffer`. 
Although `bytes.Buffer` and `strings.Builder` both have a Reset method, it cannot be used as a buffer pool because the allocation information in `strings.Builder` is rewritten as nil.
Also, `bytes.Buffer.String()` method does not have a zero-copy implementation like `strings.Builder`'s, so I decided to implement it.

**Comment by spolischook** [comment]
I would like to implement "cross fingers" strategy in which all logs would be save in pool until `action level` will reached and all logs will be fired to the writer. 
I found out that my buffer was rewritten after next write, so I got this code and was baffled why not use simple `string(buff)`. Now I see and understand it better, but will try implement it another day.
